[package]
name = "mfs16core"
version = "0.1.0"
edition = "2021"
authors = ["Max Gilmour"]
repository = "https://github.com/maxgmr/mfs16"
license-file = "LICENSE"

[dependencies]

[dev-dependencies]
pretty_assertions = "1.4"
strum = "0.26"
strum_macros = "0.26"
