[package]
name = "assembler"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1"
clap = { version = "4.5", features = ["cargo", "derive", "string"] }
codemap = "0.1"
color-eyre = "0.6"
mfs16core = { path = "../mfs16core" }
regex = "1.11"

[dev-dependencies]
pretty_assertions = "1.4"
