name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: mfs16 - latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Toolchain setup
      run: rustup update stable && rustup default stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
